language: go
sudo: false
go:
- 1.5
install:
- go get github.com/nats-io/stanserver
- go get -t ./...
- go get github.com/nats-io/gnatsd
script:
- go fmt ./...
- go vet ./...
- go test -v
#- go test -v --race
#
