language: go
sudo: false
go:
- 1.5
install:
- git clone https://122a18a6ddc85bb9001c03a377c8b273e8dc4db6@github.com/nats-io/stanserver.git /home/travis/gopath/src/github.com/nats-io/stanserver
- go get -t ./...
- go get github.com/nats-io/gnatsd
script:
- go fmt ./...
- go vet ./...
- go test -v
#- go test -v --race
#
